name: Sync EA Files

on:
  push:
    branches: [ main ]
    paths:
      - 'src/EA/**'
  schedule:
    # Täglich um 6:00 UTC (8:00 Berlin Zeit)
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Check EA Version
      run: |
        echo "Checking the_don.mq5 version..."
        grep "#property version" src/EA/the_don.mq5 || echo "EA file check"
        grep "#define release" src/EA/the_don.mq5 || echo "Release check"
    
    - name: Generate Version Info
      run: |
        VERSION=$(grep "#property version" src/EA/the_don.mq5 | cut -d'"' -f2)
        echo "Current Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Create Release Notes
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "## the_don EA v${{ env.VERSION }}" > release_notes.md
        echo "" >> release_notes.md
        echo "### Changes in this version:" >> release_notes.md
        git log --oneline -10 >> release_notes.md
        
    - name: Archive EA Files
      run: |
        mkdir -p dist
        cp -r src/EA/*.mq5 dist/
        cp -r src/Include/*.mqh dist/ 2>/dev/null || true
        tar -czf the_don_v${{ env.VERSION }}.tar.gz dist/
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: the_don_ea
        path: |
          dist/
          *.tar.gz